name: "smoke-screen-tests"
on:
  push:
    branches-ignore:
      - main

jobs:
  sst:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm test